# Node docker image on which this would be run
image: node:8.9.0

#This command is run before actual stages start running
#before_script:
#  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#  - npm install

stages:
  - migrate
  - deploy

# lint and test are two different jobs in the same stage.
# This allows us to run these two in parallel and making build faster

# Job 2:
migrate:
  stage: migrate
  before_script:
    - echo "$DOTENV_DEV" > ./.env
    - npm install
  script:
    - echo "HERES CONFIG"
    - cat .env
    - npm run migrate
  tags:
    - feedposter-be

deployToAWS:
  stage: deploy
  before_script:
    - echo "$DOTENV_DEV" > .env
  script:
    - npm i
    - npm run build
    - bash deploy/deploy.sh
  tags:
    - feedposter-be
